# /home/ubuntu/ansible/deploy_flask_app.yml

- name: Deploy Flask App in Docker on Server C
  hosts: web
  become: true

  tasks:
    - name: Pull Docker image from DockerHub
      community.docker.docker_image:
        name: nawaz1114/flask-app
        source: pull

    - name: Run Flask container
      community.docker.docker_container:
        name: flask-container
        image: nawaz1114/flask-app
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
